# Generated by Django 2.1.7 on 2019-03-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_auto_20190313_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='track',
        ),
    ]
